// automatically generated by the FlatBuffers compiler, do not modify

package im.redpanda.commands;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FBPeerList extends Table {
  public static FBPeerList getRootAsFBPeerList(ByteBuffer _bb) { return getRootAsFBPeerList(_bb, new FBPeerList()); }
  public static FBPeerList getRootAsFBPeerList(ByteBuffer _bb, FBPeerList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public FBPeerList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FBPeer peers(int j) { return peers(new FBPeer(), j); }
  public FBPeer peers(FBPeer obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int peersLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createFBPeerList(FlatBufferBuilder builder,
      int peersOffset) {
    builder.startObject(1);
    FBPeerList.addPeers(builder, peersOffset);
    return FBPeerList.endFBPeerList(builder);
  }

  public static void startFBPeerList(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addPeers(FlatBufferBuilder builder, int peersOffset) { builder.addOffset(0, peersOffset, 0); }
  public static int createPeersVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPeersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFBPeerList(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishFBPeerListBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedFBPeerListBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

