// automatically generated by the FlatBuffers compiler, do not modify

package im.redpanda.commands;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FBPublicKey extends Table {
  public static FBPublicKey getRootAsFBPublicKey(ByteBuffer _bb) { return getRootAsFBPublicKey(_bb, new FBPublicKey()); }
  public static FBPublicKey getRootAsFBPublicKey(ByteBuffer _bb, FBPublicKey obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public FBPublicKey __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte publicKey(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int publicKeyLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer publicKeyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer publicKeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createFBPublicKey(FlatBufferBuilder builder,
      int publicKeyOffset) {
    builder.startObject(1);
    FBPublicKey.addPublicKey(builder, publicKeyOffset);
    return FBPublicKey.endFBPublicKey(builder);
  }

  public static void startFBPublicKey(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addPublicKey(FlatBufferBuilder builder, int publicKeyOffset) { builder.addOffset(0, publicKeyOffset, 0); }
  public static int createPublicKeyVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startPublicKeyVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endFBPublicKey(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishFBPublicKeyBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedFBPublicKeyBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

